ALTER TABLE QRTZ_CALENDARS  DROP
  CONSTRAINT PK_QRTZ_CALENDARS ;

ALTER TABLE QRTZ_CRON_TRIGGERS  DROP
  CONSTRAINT PK_QRTZ_CRON_TRIGGERS;

ALTER TABLE QRTZ_FIRED_TRIGGERS  DROP
  CONSTRAINT PK_QRTZ_FIRED_TRIGGERS ;

ALTER TABLE QRTZ_PAUSED_TRIGGER_GRPS  DROP
  CONSTRAINT PK_QRTZ_PAUSED_TRIGGER_GRPS ;

ALTER TABLE QRTZ_SCHEDULER_STATE  DROP
  CONSTRAINT PK_QRTZ_SCHEDULER_STATE ;

ALTER TABLE QRTZ_LOCKS  DROP
  CONSTRAINT PK_QRTZ_LOCKS ;

ALTER TABLE QRTZ_JOB_DETAILS  DROP
  CONSTRAINT PK_QRTZ_JOB_DETAILS ;

ALTER TABLE QRTZ_SIMPLE_TRIGGERS  DROP
  CONSTRAINT PK_QRTZ_SIMPLE_TRIGGERS;

ALTER TABLE QRTZ_SIMPROP_TRIGGERS  DROP
  CONSTRAINT PK_QRTZ_SIMPROP_TRIGGERS ;

ALTER TABLE QRTZ_TRIGGERS  DROP
  CONSTRAINT PK_QRTZ_TRIGGERS;

ALTER TABLE QRTZ_CRON_TRIGGERS DROP
  CONSTRAINT FK_QRTZ_CRON_TRIGGERS_QRTZ_TRIGGERS;


ALTER TABLE QRTZ_SIMPLE_TRIGGERS DROP
  CONSTRAINT FK_QRTZ_SIMPLE_TRIGGERS_QRTZ_TRIGGERS ;

ALTER TABLE QRTZ_SIMPROP_TRIGGERS DROP
  CONSTRAINT FK_QRTZ_SIMPROP_TRIGGERS_QRTZ_TRIGGERS ;


ALTER TABLE QRTZ_TRIGGERS DROP
  CONSTRAINT FK_QRTZ_TRIGGERS_QRTZ_JOB_DETAILS ;

DROP TABLE QRTZ_CALENDARS;
DROP TABLE QRTZ_CRON_TRIGGERS;
DROP TABLE QRTZ_FIRED_TRIGGERS;
DROP TABLE QRTZ_PAUSED_TRIGGER_GRPS;
DROP TABLE QRTZ_SCHEDULER_STATE;
DROP TABLE QRTZ_LOCKS;
DROP TABLE QRTZ_JOB_DETAILS;
DROP TABLE QRTZ_SIMPLE_TRIGGERS;
DROP TABLE QRTZ_SIMPROP_TRIGGERS;
DROP TABLE QRTZ_BLOB_TRIGGERS;
DROP TABLE QRTZ_TRIGGERS;

COMMIT;
